### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by jvanstraten** [abs-tudelft/vhsnunzip#1]
TODO:

 - [x] finish + test buffered design
 - [x] implement + test BRAM memory style
 - [x] test multicore design
 - [x] synthesize multicore design, update resource table in readme
 - [x] more testing, (probably) more bug squashing
 - [x] run on some node or do more advanced sim runs to get performance information for multicore designs
 - ~~possibly some block diagrams for documentation~~ I'm at the point where I don't exactly remember how it works myself, so might as well close this and mark it as done.
